<div class="max-w-sm w-full bg-white rounded-lg shadow  p-4 md:p-6  border  border-gray-300">
    <div class="flex justify-between mb-3">
        <div class="flex items-center">
            <div class="flex justify-center items-center">
                <h5 class="text-xl font-bold leading-none text-gray-600  pe-1">
                    Staffs
                </h5>
                <svg data-popover-target="chart-info" data-popover-placement="bottom"
                    class="w-3.5 h-3.5 text-gray-500  hover:text-gray-900  cursor-pointer ms-1" aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                    <path
                        d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm0 16a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3Zm1-5.034V12a1 1 0 0 1-2 0v-1.418a1 1 0 0 1 1.038-.999 1.436 1.436 0 0 0 1.488-1.441 1.501 1.501 0 1 0-3-.116.986.986 0 0 1-1.037.961 1 1 0 0 1-.96-1.037A3.5 3.5 0 1 1 11 11.466Z" />
                </svg>
                <div data-popover id="chart-info" role="tooltip"
                    class="absolute z-10 invisible inline-block text-sm text-gray-500 transition-opacity duration-300 bg-white border border-gray-200 rounded-lg shadow-sm opacity-0 w-72 ">
                    <div class="p-3 space-y-2">
                        <h3 class="font-semibold text-gray-900 ">Activity growth - Incremental
                        </h3>
                        <p>Report helps navigate cumulative growth of community activities. Ideally, the chart
                            should have a growing trend, as stagnating chart signifies a significant decrease of
                            community activity.</p>
                        <h3 class="font-semibold text-gray-900 ">Calculation</h3>
                        <p>For each date bucket, the all-time volume of activities is calculated. This means
                            that activities in period n contain all activities up to period n, plus the
                            activities generated by your community in period.</p>
                        <a href="#"
                            class="flex items-center font-medium text-blue-600 hover:text-blue-700 hover:underline">Read
                            more <svg class="w-2 h-2 ms-1.5 rtl:rotate-180" aria-hidden="true"
                                xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                    stroke-width="2" d="m1 9 4-4-4-4" />
                            </svg></a>
                    </div>
                    <div data-popper-arrow></div>
                </div>
            </div>
        </div>
    </div>

    <div class="bg-gray-50  p-3 rounded-lg">
        <div class="grid grid-cols-3 gap-3 mb-2">
            <dl class="bg-orange-50  rounded-lg flex flex-col items-center justify-center h-[78px]">
                <dt
                    class="w-8 h-8 rounded-full bg-orange-100 text-orange-600  text-sm font-medium flex items-center justify-center mb-1">
                    {{ $userChart->where('role', 'admin')->count() }}</dt>
                <dd class="text-orange-600  text-sm font-medium">Admin</dd>
            </dl>
            <dl class="bg-teal-50  rounded-lg flex flex-col items-center justify-center h-[78px]">
                <dt
                    class="w-8 h-8 rounded-full bg-teal-100  text-teal-600  text-sm font-medium flex items-center justify-center mb-1">
                    {{ $userChart->where('role', 'inspector')->count() }}</dt>
                <dd class="text-teal-600  text-sm font-medium">Inspector</dd>
            </dl>
            <dl class="bg-blue-50 rounded-lg flex flex-col items-center justify-center h-[78px]">
                <dt
                    class="w-8 h-8 rounded-full bg-blue-100  text-blue-600  text-sm font-medium flex items-center justify-center mb-1">
                    {{ $userChart->where('role', 'butcher')->count() }}</dt>
                <dd class="text-blue-600  text-sm font-medium">Butcher</dd>
            </dl>
        </div>
        <button data-collapse-toggle="more-details" type="button"
            class="hover:underline text-xs text-gray-500  font-medium inline-flex items-center">Show
            more details <svg class="w-2 h-2 ms-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                viewBox="0 0 10 6">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                    d="m1 1 4 4 4-4" />
            </svg>
        </button>
        <div id="more-details" class="border-gray-200 border-t  pt-3 mt-3 space-y-2 hidden">
            <dl class="flex items-center justify-between">
                <dt class="text-gray-500  text-sm font-normal">Average task completion rate:
                </dt>
                <dd
                    class="bg-green-100 text-green-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md">
                    <svg class="w-2.5 h-2.5 me-1.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
                        viewBox="0 0 10 14">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                            d="M5 13V1m0 0L1 5m4-4 4 4" />
                    </svg> 57%
                </dd>
            </dl>
            <dl class="flex items-center justify-between">
                <dt class="text-gray-500  text-sm font-normal">Days until sprint ends:</dt>
                <dd
                    class="bg-gray-100 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md ">
                    13 days</dd>
            </dl>
            <dl class="flex items-center justify-between">
                <dt class="text-gray-500  text-sm font-normal">Next meeting:</dt>
                <dd
                    class="bg-gray-100 text-gray-800 text-xs font-medium inline-flex items-center px-2.5 py-1 rounded-md ">
                    Thursday</dd>
            </dl>
        </div>
    </div>

    <!-- Radial Chart -->
    <div class="py-6" id="radial-chart"></div>


</div>
@php

    $adminCount = $userChart->where('role', 'admin')->count();
    $inspectorCount = $userChart->where('role', 'inspector')->count();
    $butcherCount = $userChart->where('role', 'butcher')->count();
@endphp

<script>
    // ApexCharts options and config
    window.addEventListener("load", function() {

        var admin = {{ $adminCount }};
        var inspector = {{ $inspectorCount }};
        var butcher = {{ $butcherCount }};
        const getChartOptions = () => {
            return {
                series: [admin, inspector, butcher],
                colors: ["#1C64F2", "#16BDCA", "#FDBA8C"],
                chart: {
                    height: "380px",
                    width: "100%",
                    type: "radialBar",
                    sparkline: {
                        enabled: true,
                    },
                },
                plotOptions: {
                    radialBar: {
                        track: {
                            background: '#E5E7EB',
                        },
                        dataLabels: {
                            show: false,
                        },
                        hollow: {
                            margin: 0,
                            size: "32%",
                        }
                    },
                },
                grid: {
                    show: false,
                    strokeDashArray: 4,
                    padding: {
                        left: 2,
                        right: 2,
                        top: -23,
                        bottom: -20,
                    },
                },
                labels: ["Admin", "Inspector", "Butcher"],
                legend: {
                    show: true,
                    position: "bottom",
                    fontFamily: "Inter, sans-serif",
                },
                tooltip: {
                    enabled: true,
                    x: {
                        show: false,
                    },
                },
                yaxis: {
                    show: false,
                    labels: {
                        formatter: function(value) {
                            return value + '%';
                        }
                    }
                }
            }
        }

        if (document.getElementById("radial-chart") && typeof ApexCharts !== 'undefined') {
            var chart = new ApexCharts(document.querySelector("#radial-chart"), getChartOptions());
            chart.render();
        }
    });
</script>
